export const user_data = [
  {
    user_id: 1,
    name: "Aarav Sharma",
    username: "aarav_sharma",
    email: "aarav.sharma@example.com",
    country: "India",
    joined_date: "2023-09-12",
    isLive: true,
  },
  {
    user_id: 2,
    name: "Sophia Johnson",
    username: "sophie_johnson",
    email: "sophia.johnson@example.com",
    country: "USA",
    joined_date: "2024-01-05",
    isLive: false,
  },
  {
    user_id: 3,
    name: "Liam Müller",
    username: "liam_muller",
    email: "liam.muller@example.de",
    country: "Germany",
    joined_date: "2024-11-17",
    isLive: false,
  },
  {
    user_id: 4,
    name: "KodaKawa",
    username: "kodkawa",
    email: "ko.kawa@example.de",
    country: "India",
    joined_date: "2024-12-11",
    isLive: true,
  },
  {
    user_id: 5,
    name: "Tojii",
    username: "to_ji",
    email: "to@example.de",
    country: "Japan",
    joined_date: "2025-12-17",
    isLive: true,
  },
  {
    user_id: 6,
    name: "Inonix Master",
    username: "inonix",
    email: "in@example.de",
    country: "Africa",
    joined_date: "2025-1-3",
    isLive: false,
  },
  {
    user_id: 7,
    name: "Bloody Babe",
    username: "bloddy_bae",
    email: "bae@example.de",
    country: "Canada",
    joined_date: "2025-5-8",
    isLive: false,
  },
];

export const CurrentUserData = {
    user_id: 1,
    name: "Aarav Sharma",
    username: "aarav_sharma",
    email: "aarav.sharma@example.com",
    country: "India",
    joined_date: "2023-09-12",
    isLive: true,
}

export const StreamersData = [
  {
    stream_id: 101,
    title: "Building a CLI Todo App in Go",
    category: "Programming",
    thumbnail: "https://i.imgur.com/Z9q3Z3O.png",
    viewers: 1450,
    duration: "1:12:34",
    isLive: true,
    started_at: "2025-10-05T14:20:00Z",
    user: {
     user_id: 1,
    name: "Aarav Sharma",
    username: "aarav_sharma",
    email: "aarav.sharma@example.com",
    country: "India",
    joined_date: "2023-09-12",
    isLive: true,
    },
  },
  {
    stream_id: 102,
    title: "Exploring React Hooks – Beginner to Pro",
    category: "Web Development",
    thumbnail: "https://i.imgur.com/6bVvYhJ.png",
    viewers: 3210,
    duration: "2:04:11",
    isLive: true,
    started_at: "2025-09-27T18:00:00Z",
    user: {
     user_id: 3,
    name: "Liam Müller",
    username: "liam_muller",
    email: "liam.muller@example.de",
    country: "Germany",
    joined_date: "2024-11-17",
    isLive: false,
    },
  },
  {
    stream_id: 103,
    title: "AI Tools That Will Change Coding Forever",
    category: "Tech & AI",
    thumbnail: "https://i.imgur.com/5uQPw5m.png",
    viewers: 8900,
    duration: "0:58:44",
    isLive: true,
    started_at: "2025-09-30T16:00:00Z",
    user: {
    user_id: 2,
    name: "Sophia Johnson",
    username: "sophie_johnson",
    email: "sophia.johnson@example.com",
    country: "USA",
    joined_date: "2024-01-05",
    isLive: false,
    },
  },
  {
    stream_id: 104,
    title: "Chill Coding Music – Lo-Fi Stream 🎧",
    category: "Music",
    thumbnail: "https://i.imgur.com/hEJjFqV.png",
    viewers: 12700,
    duration: "Live",
    isLive: true,
    started_at: "2025-10-05T10:30:00Z",
    user: {
       user_id: 4,
    name: "KodaKawa",
    username: "kodkawa",
    email: "ko.kawa@example.de",
    country: "India",
    joined_date: "2024-12-11",
    isLive: true,
    },
  },
  {
    stream_id: 105,
    title: "Deploying Full Stack Apps with Docker & AWS",
    category: "DevOps",
    thumbnail: "https://i.imgur.com/ahGq3aN.png",
    viewers: 4320,
    duration: "1:45:10",
    isLive: false,
    started_at: "2025-09-29T12:15:00Z",
    user: {
    user_id: 6,
    name: "Inonix Master",
    username: "inonix",
    email: "in@example.de",
    country: "Africa",
    joined_date: "2025-1-3",
    isLive: false,
    },
  },
  {
    stream_id: 106,
    title: "German Tech Meetup: Go vs Rust – Who Wins?",
    category: "Discussion",
    thumbnail: "https://i.imgur.com/6UJH4mE.png",
    viewers: 2100,
    duration: "1:20:03",
    isLive: false,
    started_at: "2025-09-21T19:00:00Z",
    user: {
    user_id: 7,
    name: "Bloody Babe",
    username: "bloddy_bae",
    email: "bae@example.de",
    country: "Canada",
    joined_date: "2025-5-8",
    isLive: false,
    },
  },
];
